---
title: "functions"
author: "Xuehan Yang"
date: "2021/11/16"
output: github_document
---

```{r, message=FALSE}
library(tidyverse)
library(rvest)

set.seed(1)
```

## My first function

```{r}
x_vec = rnorm(50, mean = 5, sd = 3)

(x_vec - mean(x_vec))/sd(x_vec)
```

```{r, warning=FALSE}
z_score = function(x){
  z = (x - mean(x))/sd(x)
  return(z)
}
```

```{r, error=TRUE, warning=FALSE}
z_score(x_vec)

z_score(3)

z_score("Sean")

z_score(iris)

z_score(sample(c(TRUE, FALSE), 25, replace = TRUE))
```

check the argument calues using conditional statements.

```{r}
z_scores = function(x){
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric!")
  } else if (length(x) == 1) {
    stop("Z score cannot be computed for length 1 vectors")
  }

z = mean(x) / sd(x)

z
}
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
   if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  list(mean = mean_x, sd = sd_x)
  
  #tibble(mean = mean_x, sd = sd_x)
}
```

```{r}
mean_and_sd(x_vec)
```

## Multiple inputs

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 2, sd = 3)
)

sim_data %>% 
  summarise(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )
```

```{r}
sim_mean_sd = function(n, mu=2, sigma=2) {
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )
  
  sim_data %>% 
    summarise(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}

sim_mean_sd(1000,2,2)
```

## Scraping Amazon

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=10"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

```{r}
read_page_reviews <- function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

dynamite_reviews
```

## Functions as arguments

```{r}
x_vec = rnorm(25, 0, 1)

my_summary = function(x, summ_func) {
  summ_func(x)
}

my_summary(x_vec, sd)

my_summary(x_vec, IQR)
```

## Scoping and names

```{r}
f = function(x) {
  #y = 80
  z = x + y
  z
}

x = 1
y = 2

f(x = y)
```











